repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.1
    hooks:
      - id: pydoclint
        args: [--style=google]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - .github/license_header.txt
          - --use-current-year

  - repo: local # mypy should run locally
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
