name: Run Tests
on:
  push:
    branches: ["main", "ci/**"]
  pull_request:
    branches: ["*"]
jobs:
  test-deepsolid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: netobs
      - uses: actions/checkout@v4
        with:
          repository: bytedance/deepsolid
          ref: b1abaf5212e1bfe1ce01257a81bc63b820efc4d4
          path: deepsolid
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install
        run: |
          pip install 'jax[cpu]'==0.2.26 -f https://storage.googleapis.com/jax-releases/jax_releases.html
          pip install -e deepsolid opt_einsum==3.3.0
          pip install -e 'netobs[dev]'
      - name: Test
        working-directory: netobs
        run: pytest --snapshot-warn-unused
  test-ferminet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: netobs
      - uses: actions/checkout@v4
        with:
          repository: google-deepmind/ferminet
          ref: c6f9db52fbb15cee01fd83c958230d27d61bfe70
          path: ferminet
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install jax==0.4.38
          pip install -e ferminet
          pip install -e 'netobs[dev]'
      - name: Test
        working-directory: netobs
        run: pytest --snapshot-warn-unused
